# frozen_string_literal: true

source 'https://rubygems.org'

# Framework web leve para criar APIs
gem 'sinatra', '~> 3.1'

# Servidor web
gem 'puma', '~> 6.4'

# SQLite3 - Banco de dados
gem 'sqlite3', '~> 1.6'

# JSON parsing
gem 'json', '~> 2.6'

# Recarregar automaticamente durante desenvolvimento
gem 'rerun', '~> 0.14', group: :development

# HTTP client para testes
gem 'httparty', '~> 0.21', group: :development
